name: Build Kivy app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Buildozer project directory
        run: mkdir .buildozer

      - name: Copy buildozer.spec file
        run: cp buildozer.spec .buildozer/buildozer.spec

      - name: Build Kivy app
        run: buildozer build
